### ISSUE TITLE
Saving between sessions

### ISSUE THREAD

**Issue by Itekiwoshi** [rkusa/dcs-scratchpad#22] opened 2022-04-24 07:44 UTC
Using the latest update was finding it didn't save between sessions.

"The changes to your Scratchpad are not saved on every keystroke anymore, instead they are only saved when hiding the Scratchpad, changing the active Scratchpad page, or removing the focus from the text field."

**Comment by rkusa** [comment] 2022-04-25 07:17
Hi, thanks for the report. However, I don't see any issue with saving between sessions myself. I am afraid we have to keep this open for now until we more details / more people jump in confirming the same issue.

**Comment by rkusa** [comment] 2022-09-04 13:11
I'll close this as cannot reproduce for now. If anyone encounters this, please confirm and if possible, add steps to reproduce.

**Closed by rkusa** 2022-09-04 13:11 UTC
