### ISSUE TITLE
Closing Window with Focus on it

### ISSUE THREAD

**Issue by Der-Orso** [rkusa/dcs-scratchpad#5] opened 2019-08-04 08:07 UTC
If you close the window with the input-focus still on it, the input-focus is locked to the now closed window, which can lead to some very bad things -- for the user. It feels like DCS had gone crazy, bc so many things then do not work.

Suggestion: rescind the focus (emulate <Esc>) on close.

**Comment by rkusa** [comment] 2019-08-13 18:28
That is strange! I am unable to reproduce. When I close the Scratchpad the focus is always removed correctly. Code doing that looks also good https://github.com/rkusa/dcs-scratchpad/blob/master/Scripts/Hooks/scratchpad-hook.lua#L173-L177 🤔

**Comment by Der-Orso** [comment] 2019-08-19 16:43
I'll have to try it again. Maybe there's some influence through SRS as well, because I'm using both at the same time practically always.

I recently had it happen again -- a couple of days ago--, and couldn't even open Scratchpad again, but I don't recall having tried to do anything with SRS at the time either.

BTW I don't code lua -- never gotten around to learning this weird world of OO programming o.O -- maybe one day. I want to write a simple add-on to manage button modifiers, if I ever get around to it.

**Comment by Der-Orso** [comment] 2019-10-26 16:54
BTW I just wanted to give a little update on this issue. I ran into it
again and I think is only has to do with the mouse pointer escaping the
DCS "window" while clicking near the edge of the visible area in VR.
Somehow the input focus is moved to Windows™ with possible catastrophic
results.

I have the -mouse pointer doesn't escape window- setting active, but I
recall reading that for that to actually work 100% of the time, you have
to be in "real full-screen" mode, because in DCS there is apparently
"DCS full screen" and "real full screen"... yeah... and I always forget
to turn that on (RCtrl-Enter iirc).

**Comment by rkusa** [comment] 2019-11-18 16:05
That is strange, I don't use DCS in full-screen mode and also in VR and for me it is impossible to click outside the window. While I remember it happened a while ago in DCS, it was apparently fixed for me. Anyway, thanks for the update, I'll still check whether I can reproduce it by explicitly trying to click outside of the DCS window 👍

**Comment by TheBlackFox27** [comment] 2022-07-30 12:47
I don't know if my issue is similar or not but I do get an issue with the DCS chat not closing and for example F10 not working. I didn't think it was because of this plugin before until someone I know installed it and got the same issue.

**Comment by rkusa** [comment] 2022-07-31 08:16
@TheBlackFox27 As long as the text field of the Scratchpad has focus, it captures all (or at least most) keyboard inputs. You probably have to remove the focus before using the shortcuts to close the chat or open the F10 map.

**Comment by rkusa** [comment] 2022-09-04 13:16
Closing for now as cannot-reproduce. If anyone encountered this, too, please still add your evidence, thanks!

**Closed by rkusa** 2022-09-04 13:16 UTC
