### ISSUE TITLE
Deleting

### ISSUE THREAD

**Issue by speed-of-heat** [rkusa/dcs-scratchpad#39] opened 2022-10-17 16:34 UTC
When deleting Text all is fine except for two cases

1) the use of  "°" sends the whole editing into a bit of a tizzy , deleting it causes  enter to fail to work correctly for example, it also resets the text input to the upper left

2) when you delete text, using the BSP function, that was created in a previous session, it seems to lose the cursors index for the page?  

Repro steps

1) record some text in scratchpad
2) leave dcs
3) go back in to DCS add more text (on a new line)
4) delete the text try and delete the text that was there in the previous session,

 it does not seem to let you go to that line ...

**Comment by rkusa** [comment] 2022-10-21 10:56
Are you referring to editing with an actual keyboard or with a virtual keyboard using #35?

**Comment by speed-of-heat** [comment] 2022-10-21 11:36
Virtual keyboard, but between sessions so edit in session 1) amend in session 2)

Thanks,
Stuart

Get Outlook<https://aka.ms/sdimjr> for iOS
________________________________

**Comment by rkusa** [comment] 2022-12-06 11:09
>     1. the use of  "°" sends the whole editing into a bit of a tizzy , deleting it causes  enter to fail to work correctly for example, it also resets the text input to the upper left

Should be fixed, can you test again? 

>     2. when you delete text, using the BSP function, that was created in a previous session, it seems to lose the cursors index for the page?

Cannot reproduce. Maybe the fix for the above issue fixed that as well. Please retest again, too.

[Download latest version](https://github.com/rkusa/dcs-scratchpad/archive/refs/heads/extensions.zip)

**Comment by speed-of-heat** [comment] 2022-12-10 10:39
Hi Apologies for the lag, I was out with COVID.  But yes this seems to resolve both issues, many thanks!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Closed** 2022-12-18 09:44 UTC
